/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: 'doc',
      label: 'Home',
      id: 'index',
    },
    {
      type: 'link',
      label: 'Pravila',
      href: '/docs/pravila',
    },
    {
      type: 'link',
      label: 'Donacije',
      href: '/docs/donacije',
    },
  ],
  pravila: [
    {
      type: 'link',
      label: '← Home',
      href: '/docs',
    },
    {
      type: 'category',
      label: 'Pravila',
      link: {
        type: 'generated-index',
        title: 'Pravila',
        description: 'Pravila',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'pravila',
        },
      ],
    },
  ],
  donacije: [
    {
      type: 'link',
      label: '← Home',
      href: '/docs',
    },
    {
      type: 'category',
      label: 'Donacije',
      link: {
        type: 'generated-index',
        title: 'Donacije',
        description: 'Donacijes',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'donacije',
        },
      ],
    },
  ],
};

module.exports = sidebars;
